CREATE TABLE [dbo].[Appointment] (
    [idappointment]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [idparamedisspesialis] BIGINT         DEFAULT ((0)) NOT NULL,
    [idjadwalsesi]         BIGINT         DEFAULT ((0)) NOT NULL,
    [idregistrasi]         BIGINT         DEFAULT ((0)) NOT NULL,
    [appointmentdate]      DATETIME       DEFAULT (getdate()) NOT NULL,
    [bookingdate]          DATETIME       DEFAULT (getdate()) NOT NULL,
    [bookingenddate]       DATETIME       DEFAULT (NULL) NULL,
    [bookingstatus]        BIGINT         DEFAULT ((0)) NOT NULL,
    [durasi]               BIGINT         DEFAULT ((0)) NOT NULL,
    [nomorurut]            BIGINT         DEFAULT ((0)) NOT NULL,
    [idrekammedis]         BIGINT         DEFAULT ((0)) NOT NULL,
    [nama]                 VARCHAR (300)  DEFAULT ('-') NOT NULL,
    [tanggallahir]         DATE           DEFAULT (getdate()) NOT NULL,
    [telepon1]             VARCHAR (30)   DEFAULT ((0)) NOT NULL,
    [telepon2]             VARCHAR (30)   DEFAULT ((0)) NOT NULL,
    [jeniskelamin]         BIGINT         NOT NULL,
    [idnegara]             BIGINT         DEFAULT ((0)) NOT NULL,
    [idpropinsi]           BIGINT         DEFAULT ((0)) NULL,
    [idkabupaten]          BIGINT         DEFAULT ((0)) NULL,
    [idkecamatan]          BIGINT         DEFAULT ((0)) NULL,
    [idkelurahan]          BIGINT         DEFAULT ((0)) NULL,
    [alamat]               VARCHAR (2000) DEFAULT ('-') NOT NULL,
    [remarks]              VARCHAR (5000) DEFAULT ('-') NOT NULL,
    [appremarks]           VARCHAR (30)   DEFAULT ('-') NOT NULL,
    [issms]                BIGINT         DEFAULT ((0)) NOT NULL,
    [issmssent]            BIGINT         DEFAULT ((0)) NOT NULL,
    [isdeleted]            BIGINT         DEFAULT ((0)) NOT NULL,
    [deletereason]         VARCHAR (200)  DEFAULT ('-') NOT NULL,
    [rating]               INT            CONSTRAINT [DF__Appointme__ratin__3E131840] DEFAULT ((0)) NOT NULL,
    [createdby]            BIGINT         DEFAULT ((0)) NOT NULL,
    [createddate]          DATETIME       DEFAULT (getdate()) NOT NULL,
    [updatedby]            BIGINT         NULL,
    [updateddate]          DATETIME       NULL,
    [idcompany]            BIGINT         DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([idappointment] ASC)
);

