CREATE TABLE [dbo].[Pengajuan] (
    [idpengajuan]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [idcoa]            BIGINT          NULL,
    [nopengajuan]      VARCHAR (15)    NULL,
    [tanggalpengajuan] DATETIME        NULL,
    [jumlahuang]       DECIMAL (20, 2) NULL,
    [hurufuang]        VARCHAR (5000)  NULL,
    [idpemohon]        BIGINT          NULL,
    [idunitpemohon]    BIGINT          NULL,
    [namapemohon]      VARCHAR (300)   NULL,
    [jabatanpemohon]   VARCHAR (250)   NULL,
    [deptpemohon]      VARCHAR (150)   NULL,
    [keperluan]        VARCHAR (5000)  NULL,
    [idreview]         BIGINT          NULL,
    [idunitreview]     BIGINT          NULL,
    [namareview]       VARCHAR (300)   NULL,
    [jabatanreview]    VARCHAR (250)   NULL,
    [deptreview]       VARCHAR (150)   NULL,
    [tanggalreview]    DATETIME        NULL,
    [idkabid]          BIGINT          NULL,
    [namakabid]        VARCHAR (300)   NULL,
    [jabatankabid]     VARCHAR (250)   NULL,
    [deptkabid]        VARCHAR (150)   NULL,
    [tanggalkabid]     DATETIME        NULL,
    [iddirektur]       BIGINT          NULL,
    [namadirektur]     VARCHAR (300)   NULL,
    [jabatandirektur]  VARCHAR (250)   NULL,
    [deptdirektur]     VARCHAR (150)   NULL,
    [tanggaldirektur]  DATETIME        NULL,
    [isdeleted]        BIGINT          NULL,
    [isreviewed]       BIGINT          NULL,
    [rejectreason]     VARCHAR (500)   NULL,
    [tipepengajuan]    BIGINT          DEFAULT ((1)) NULL,
    [idcompany]        BIGINT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([idpengajuan] ASC)
);

