CREATE TABLE [dbo].[JadwalParamedis] (
    [idjadwalparamedis]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [idjadwalsesi]         BIGINT        DEFAULT ((0)) NOT NULL,
    [idparamedis]          BIGINT        DEFAULT ((0)) NOT NULL,
    [idparamedispengganti] BIGINT        DEFAULT ((0)) NOT NULL,
    [idlokasi]             BIGINT        DEFAULT ((0)) NOT NULL,
    [idlokasipengganti]    BIGINT        DEFAULT ((0)) NOT NULL,
    [jadwaltanggal]        DATE          DEFAULT (getdate()) NOT NULL,
    [jammulai]             TIME (7)      DEFAULT (CONVERT([varchar],getdate(),(108))) NOT NULL,
    [jamselesai]           TIME (7)      DEFAULT (CONVERT([varchar],getdate(),(108))) NOT NULL,
    [jammulairealisasi]    TIME (7)      DEFAULT (NULL) NULL,
    [jamselesairealisasi]  TIME (7)      DEFAULT (NULL) NULL,
    [jammulaipengganti]    TIME (7)      DEFAULT (NULL) NULL,
    [jamselesaipengganti]  TIME (7)      DEFAULT (NULL) NULL,
    [statuskamar]          BIGINT        DEFAULT ((0)) NOT NULL,
    [remarks]              VARCHAR (300) DEFAULT ('-') NOT NULL,
    [isdeleted]            BIGINT        DEFAULT ((0)) NOT NULL,
    [createdby]            BIGINT        DEFAULT ((0)) NOT NULL,
    [createddate]          DATETIME      DEFAULT (getdate()) NOT NULL,
    [updatedby]            BIGINT        NULL,
    [updateddate]          DATETIME      NULL,
    [idcompany]            BIGINT        DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([idjadwalparamedis] ASC)
);

