CREATE TABLE [dbo].[Assessment] (
    [idassessment]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [idregistrasi]       BIGINT         DEFAULT ((0)) NOT NULL,
    [assessmenttype]     BIGINT         DEFAULT ((0)) NOT NULL,
    [skalatriage]        BIGINT         DEFAULT ((0)) NOT NULL,
    [tanggaldatang]      DATETIME       DEFAULT (getdate()) NOT NULL,
    [tanggalkejadian]    DATETIME       DEFAULT (getdate()) NOT NULL,
    [gcse]               BIGINT         DEFAULT ((0)) NOT NULL,
    [gcsv]               BIGINT         DEFAULT ((0)) NOT NULL,
    [gcsm]               BIGINT         DEFAULT ((0)) NOT NULL,
    [iskesadaran]        BIGINT         CONSTRAINT [DF__Assessmen__kesad__4D6A6A69] DEFAULT ((0)) NOT NULL,
    [pupila]             BIGINT         DEFAULT ((0)) NOT NULL,
    [pupilb]             BIGINT         DEFAULT ((0)) NOT NULL,
    [isrefcahaya]        BIGINT         DEFAULT ((0)) NOT NULL,
    [tdsis]              BIGINT         DEFAULT ((0)) NOT NULL,
    [tddias]             BIGINT         DEFAULT ((0)) NOT NULL,
    [denyutnadi]         BIGINT         DEFAULT ((0)) NOT NULL,
    [isnadi]             BIGINT         DEFAULT ((0)) NOT NULL,
    [suhu]               DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [nafas]              BIGINT         DEFAULT ((0)) NOT NULL,
    [oksigendarah]       BIGINT         DEFAULT ((0)) NOT NULL,
    [isakral]            BIGINT         CONSTRAINT [DF__Assessmen__akral__57E7F8DC] DEFAULT ((0)) NOT NULL,
    [isalergi]           BIGINT         DEFAULT ((0)) NOT NULL,
    [alergi]             VARCHAR (500)  DEFAULT ('-') NOT NULL,
    [alergireaksi]       VARCHAR (500)  DEFAULT ('-') NOT NULL,
    [isgangguanperilaku] BIGINT         DEFAULT ((0)) NOT NULL,
    [isperilakubahaya]   BIGINT         DEFAULT ((0)) NOT NULL,
    [isinformasi]        BIGINT         DEFAULT ((0)) NOT NULL,
    [iscaramasuk]        BIGINT         DEFAULT ((0)) NOT NULL,
    [ispengantar]        BIGINT         DEFAULT ((0)) NOT NULL,
    [ispenyebab]         BIGINT         DEFAULT ((0)) NOT NULL,
    [penyebab]           VARCHAR (500)  DEFAULT ('-') NOT NULL,
    [isdeleted]          BIGINT         DEFAULT ((0)) NOT NULL,
    [createdby]          BIGINT         DEFAULT ((0)) NOT NULL,
    [createddate]        DATETIME       DEFAULT (getdate()) NOT NULL,
    [updatedby]          BIGINT         NULL,
    [updateddate]        DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([idassessment] ASC)
);

