CREATE TABLE [dbo].[Registrasi] (
    [idregistrasi]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [idregistrasiparent] BIGINT        DEFAULT ((0)) NOT NULL,
    [transactiontype]    BIGINT        DEFAULT ((0)) NOT NULL,
    [idrekammedis]       BIGINT        DEFAULT ((0)) NOT NULL,
    [idlokasi]           BIGINT        DEFAULT ((0)) NOT NULL,
    [iddokterruangan]    BIGINT        DEFAULT ((0)) NOT NULL,
    [iddokterrujukan]    BIGINT        DEFAULT ((0)) NULL,
    [registrasidate]     DATETIME      DEFAULT (getdate()) NOT NULL,
    [registrasino]       VARCHAR (50)  DEFAULT ('-') NOT NULL,
    [kunjunganke]        BIGINT        DEFAULT ((0)) NOT NULL,
    [kunjunganlokasike]  BIGINT        DEFAULT ((0)) NOT NULL,
    [asalpx]             BIGINT        DEFAULT ((0)) NOT NULL,
    [asalpx2]            BIGINT        DEFAULT ((0)) NOT NULL,
    [asalrujukan]        BIGINT        DEFAULT ((0)) NOT NULL,
    [jeniskunjungan]     BIGINT        DEFAULT ((0)) NOT NULL,
    [registrasistatus]   BIGINT        DEFAULT ((0)) NOT NULL,
    [remarks]            VARCHAR (300) DEFAULT ('-') NOT NULL,
    [payertype]          BIGINT        DEFAULT ((0)) NOT NULL,
    [idpayer]            BIGINT        DEFAULT ((0)) NOT NULL,
    [ishamil]            BIGINT        DEFAULT ((0)) NOT NULL,
    [isdeleted]          BIGINT        DEFAULT ((0)) NOT NULL,
    [deletereason]       VARCHAR (200) DEFAULT ('-') NOT NULL,
    [createdby]          BIGINT        DEFAULT ((0)) NOT NULL,
    [createddate]        DATETIME      DEFAULT (getdate()) NOT NULL,
    [updatedby]          BIGINT        NULL,
    [updateddate]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([idregistrasi] ASC)
);

