CREATE TABLE [dbo].[Transaksi] (
    [idtransaksi]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [idtransaksireff]       BIGINT          NULL,
    [transaksitype]         BIGINT          NOT NULL,
    [transaksitypereff]     BIGINT          NULL,
    [idunitasal]            BIGINT          NULL,
    [unitasal]              VARCHAR (150)   NULL,
    [idunittujuan]          BIGINT          NULL,
    [unittujuan]            VARCHAR (150)   NULL,
    [idbusinesspartner]     BIGINT          NULL,
    [businesspartnertype]   BIGINT          NULL,
    [transaksino]           VARCHAR (50)    NOT NULL,
    [transaksistatus]       BIGINT          NOT NULL,
    [kodepartner]           VARCHAR (20)    NULL,
    [namapartner]           VARCHAR (500)   NULL,
    [npwp]                  VARCHAR (50)    NULL,
    [phone]                 VARCHAR (50)    NULL,
    [email]                 VARCHAR (500)   NULL,
    [alamat]                VARCHAR (2000)  NULL,
    [contactperson]         VARCHAR (500)   NULL,
    [paymenttype]           BIGINT          NULL,
    [isdeleted]             BIGINT          NOT NULL,
    [remarks]               VARCHAR (500)   NOT NULL,
    [subtotal]              DECIMAL (20, 2) NULL,
    [discglobal]            DECIMAL (20, 2) NULL,
    [discsubtotal]          DECIMAL (20, 2) NULL,
    [subtotaldisc]          DECIMAL (20, 2) NULL,
    [ppnsubtotal]           DECIMAL (20, 2) NULL,
    [subtotaldiscppn]       DECIMAL (20, 2) NULL,
    [ongkir]                DECIMAL (20, 2) NULL,
    [subtotaldiscppnongkir] DECIMAL (20, 2) NULL,
    [createdby]             BIGINT          NOT NULL,
    [createddate]           DATETIME        NOT NULL,
    [createdfromip]         VARCHAR (20)    NOT NULL,
    [createdfromhostname]   VARCHAR (300)   NOT NULL,
    [updatedby]             BIGINT          NULL,
    [updateddate]           DATETIME        NULL,
    [updatedfromip]         VARCHAR (20)    NULL,
    [updatedfromhostname]   VARCHAR (300)   NULL,
    [reviewedby]            BIGINT          NULL,
    [revieweddate]          DATETIME        NULL,
    [reviewedfromip]        VARCHAR (20)    NULL,
    [reviewedfromhostname]  VARCHAR (300)   NULL,
    [hashcode]              VARCHAR (1000)  NULL,
    [iddepartmentasal]      BIGINT          NULL,
    [departmentasal]        VARCHAR (150)   NULL,
    [iddepartmenttujuan]    BIGINT          NULL,
    [departmenttujuan]      VARCHAR (150)   NULL,
    PRIMARY KEY CLUSTERED ([idtransaksi] ASC)
);

